### PR TITLE
spelling typo

### PR DESCRIPTION
**Pull request by absurdtiger**
I'm so confused so if I fork and make a push it doesn't give you the suggestion asodieoij

### CODE REVIEW

**Review by Mini-Ware — APPROVED** [review]
lol thank you!

**Comment by duckupus** [comment]
:D congrats on your first PR!

**Comment by absurdtiger** [comment]
damn what about #11 tho

**Comment by duckupus** [comment]
# We are working on it!
- Dont need to worry
- Dont need to panic
- I dont know what I am doing with this now

**Pull request merged**
